# Generated by Django 4.2.1 on 2023-05-21 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='command',
            name='product',
        ),
        migrations.RemoveField(
            model_name='commanddetails',
            name='commad',
        ),
        migrations.RemoveField(
            model_name='deliveryinformation',
            name='commad',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Command',
        ),
        migrations.DeleteModel(
            name='CommandDetails',
        ),
        migrations.DeleteModel(
            name='DeliveryInformation',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
