# Generated by Django 4.2.1 on 2023-06-10 00:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pannier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pannierNum', models.PositiveIntegerField(default=0)),
                ('productNum', models.PositiveIntegerField(default=1)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('dateAdd', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'pannier',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('password', models.CharField(default='', max_length=50)),
                ('email', models.EmailField(default='', max_length=254)),
                ('phone', models.TextField(default='', max_length=20)),
                ('address', models.TextField(default='', max_length=20)),
                ('firstName', models.CharField(default='', max_length=50)),
                ('lastName', models.CharField(default='', max_length=50)),
                ('typeClient', models.CharField(choices=[('LOYAL', 'Loyal Customer'), ('Normall', 'Normal Customer'), ('VIP', ' Vip Customer')], default='Normal', max_length=50)),
                ('clientProduct', models.ManyToManyField(through='base.Command', to='base.product')),
                ('pannier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.pannier')),
            ],
            options={
                'db_table': 'client',
            },
        ),
        migrations.AddField(
            model_name='command',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.client'),
        ),
    ]
